#ifndef PARTITIONS_CONFIG_H
#define PARTITIONS_CONFIG_H
/*flash分区配置表

flash分区排布：
|----OTA1----|----OTA2----|----CONFIG----|--device id--|

*/

#define PARTITIONS_FLASH_SIZE_4M 	4
#define PARTITIONS_FLASH_SIZE_8M 	8
#define PARTITIONS_FLASH_SIZE_16M 	16

//分区大小
//#define PARTITIONS_TOTAL_SIZE 	(PARTITIONS_FLASH_SIZE_4M*1024*1024)
//#define PARTITIONS_APP_SIZE		0x3C0000//3.75M

//OTA分区1 2.5M
#define PARTITIONS_ADDR_OTA1 	OTA_UPGRADE_ADDR
#define PARTITIONS_SIZE_OTA1 	OTA_UPGRADE_AREA_SIZE

//OTA分区2 2.5M
//#define PARTITIONS_ADDR_OTA2 	(PARTITIONS_ADDR_OTA1 + PARTITIONS_SIZE_OTA1)
//#define PARTITIONS_SIZE_OTA2 	PARTITIONS_APP_SIZE

//flash配置参数分区 128kb
//#define PARTITIONS_SIZE_CONFIG 	0x20000
//#define PARTITIONS_ADDR_CONFIG 	(PARTITIONS_TOTAL_SIZE - PARTITIONS_SIZE_CONFIG)

//配置参数1
#define PARTITIONS_ADDR_CONFIG_1 RDA_USER_DATA_ADDR
#define PARTITIONS_SIZE_CONFIG_1 RDA_USER_DATA_LENG

//配置参数2
//#define PARTITIONS_ADDR_CONFIG_2 (PARTITIONS_ADDR_CONFIG_1 + PARTITIONS_SIZE_CONFIG_1)
//#define PARTITIONS_SIZE_CONFIG_2 (4*1024)

//存储device id分区（存储在flash最后）
//#define PARTITIONS_SIZE_DEVICE_QNIQUE_ID	(1024)
//#define PARTITIONS_ADDR_DEVICE_QNIQUE_ID	(PARTITIONS_TOTAL_SIZE - PARTITIONS_SIZE_DEVICE_QNIQUE_ID)

#endif

